on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - name: Install apt-get dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          wget \
          pkg-config \
          git \
          cryptsetup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Install Singularity
        run: |
          export VERSION=3.5.3 && # adjust this as necessary \
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
          tar -xzf singularity-${VERSION}.tar.gz && \
          cd singularity && \
          ./mconfig && \
          make -C builddir && \
          sudo make -C builddir install
      - name: Decrypt sylabs token
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SYLABS_TOKEN: ${{ secrets.SYLABS_TOKEN }}

      - name: Ensure the token in properly decrypted
        run: |
         singularity remote login --tokenfile $HOME/secrets/sylabs-token

      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Set up conda environment
        shell: bash -l {0}
        run: |
          python -m pip install -e .
          conda list

      - name: Build and Push Test
        shell: bash -l {0}
        run: |
         repo2singularity --image-name binder-examples-continuous-build https://github.com/binder-examples/continuous-build

      # - name: Pull Test
      #   shell: bash -l {0}
      #   run: |
      #    singularity pull library://andersy005/test/binder-examples-continuous-build:latest
