name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        repo-type:
          - conda
          - dockerfile
    steps:
      - uses: actions/checkout@v2
      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: "latest"
          environment-file: ci/environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install repo2apptainer
        run: |
          python -m pip install -e . --no-deps --force-reinstall
          conda list

      - name: Run tests
        run: |
          cd tests
          repo2apptainer build ${{ matrix.repo-type }}
          docker run --privileged --rm -v ~/.singularity/cache/:/work kaczmarj/apptainer:1.0.0 exec r2s-${{ matrix.repo-type }}-main.sif conda --version
